---
title: "R for Humanities: Lesson 6"
output: 
  html_notebook: 
    number_sections: true
---

[View this page in a browser](https://htmlpreview.github.io/?https://github.com/argentenum/Rworkshop/blob/master/notebooks/RforHumanities06.nb.html)

[Go to Lesson 5](https://htmlpreview.github.io/?https://raw.githubusercontent.com/argentenum/Rworkshop/master/notebooks/RforHumanities05.nb.html)


#regular expressions
pnpWords[42]
#substr
substr(pnpWords[42],1,9)
#strsplit
strsplit(pnpWords[42], split = "r")
strsplit("these are a few of my favourite things", split = " ")
str(strsplit("these are a few of my favourite things", split = " "))
unlist(strsplit("these are a few of my favourite things", split = " "))
#readlines
pnpText <- readLines("https://web.iitd.ac.in/~arjunghosh/RworkshopFiles/pnp.txt")
#parse sentences
strsplit(pnpText, "\\.")
#read sonnets
sonnets <- readLines("https://www.gutenberg.org/files/1041/1041-0.txt")
sonnets[328:341]
#trim white space
trimws(sonnets[328:341])
sonnets <- trimws(sonnets)
#grep
grep("Shall I compare", sonnets)
#sprintf()
i <- 8
sprintf("the square of %d is %d",i,i^2)
#regexpr ???
regexpr("uat","Equator")
#gregexpr
gregexpr("iss", "Mississipi")
#sub replace substring - only first instance
sub("iss","ant","Mississipi")
#gsub replace substrings - all instances
gsub("iss","ant","Mississipi")
#from sonnets identify sonnet lines and create a list with each sonnet as one column of the list
