---
title: "R for Humanities: Map plotting"
output: 
  html_notebook: 
    number_sections: true
editor_options: 
  markdown: 
    wrap: 72
---

[Main
Menu](https://htmlpreview.github.io/?https://github.com/argentenum/Rworkshop/blob/master/notebooks/RforHumanities.nb.html)


[Georeferencing](https://map-rfun.library.duke.edu/01_georeference.html)

For plotting points on a map we need to install and run two libraries

```{r}
library(sf)
library(mapview)
```


# reading the data

```{r}
lifeDF <- read.csv("./data/cleanoutput.csv", stringsAsFactors = FALSE)
```

In 'mapview' the coordintes are pushed separately as Longtitude and Latitude in decimal format.

# converting data into spatial objects
```{r}
birthLoc <- st_as_sf(lifeDF, coords = c("birthlon","birthlat"),
                     crs=4326)
deathLoc <- st_as_sf(lifeDF, coords = c("deathlon","deathlat"),
                     crs=4326)
```


#plotting the map

## just one type of location

```{r}
mapview(birthLoc)
```

## multiple location types

```{r}
mapview(list(birthLoc,deathLoc),col.regions=list("blue","red"),col=list("blue","red"),label=lifeDF$Name)
```




[Main
Menu](https://htmlpreview.github.io/?https://github.com/argentenum/Rworkshop/blob/master/notebooks/RforHumanities.nb.html)